export const skills = [
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "JavaScript (ES6 + Features)",
  "CSS FlexBox",
  "CSS Grid",
  "CSS BEM convention",
  "Immutability",
  "React Router",
  "React",
  "Redux-Saga",
  "Create React App",
  "Create Vite",
  "Redux (Toolkit)",
  "Error handling",
  "React Hooks",
  "Custom React Hooks",
  "Working with API (fetch, axios)",
  "Promises, Async / Await",
  "Git",
  "NPM & PNPM",
  "Styled-Components",
];
