const skills = [
  "HTML",
  "CSS",
  "JavaScript (ES6 + Features)",
  "FlexBox",
  "Grid",
  "Immutability",
  "Media Queries",
  "React",
  "Create React App",
  "Babel",
  "Webpack",
  "React Hooks: useRef, useState",
  "Custom Hooks",
  "Styled-Components",
  "Local Storage",
  "Redux Toolkit",
  "Redux Saga",
  "React Route",
  "Generator functions",
  "Async functions",
  "Axios",
];

export { skills };
